Add Get merchantsAccount list
Adyen/adyen-php-api-library pull request #331
Opened 2022-02-22 10:06 UTC by AlexandrosMor

**Description**

- Extend CurlClient to support rest api methods
- Add management api merchants Account list

**Tested scenarios**

**Fixed issue**:

2022-02-24 08:16 UTC, acampos1916 commented on src/Adyen/HttpClient/CurlClient.php
> +        return $this->requestHttp($service, $requestUrl, $params, 'post', $requestOptions);
`$requestOptions` doesn't seem to be an arg in the ClientInterface function?

2022-02-24 08:36 UTC, acampos1916 commented on src/Adyen/Service/AbstractResource.php
> +            $msg = 'The rest api method is empty';
```suggestion
            $msg = 'The REST API method is empty';
```

2022-02-24 08:44 UTC, acampos1916 commented on tests/Integration/ManagementTest.php
> +            "url" => "https://magento2-devx.ataberkylmz.com/",
Can we supply a non working URL here instead or does this service also test the webhook being accepted?

2022-02-24 17:19 UTC, AlexandrosMor commented on tests/Integration/ManagementTest.php
> +            "url" => "https://magento2-devx.ataberkylmz.com/",
```suggestion
            "url" => "https://testwebsite.com/",
```

2022-02-24 20:14 UTC, michaelpaul requested changes
It's looking good! I'm just leaving a few suggestions.

2022-02-24 20:14 UTC, michaelpaul commented on src/Adyen/Service/ResourceModel/Management/MerchantClientKey.php
> +    }
I think path parameters should come before body params for this and other POST requests.: 
```suggestion
    public function create($merchantId, $apiCredentialId, $params)
    {
        $url = $this->managementEndpoint . "/merchants/" . $merchantId . "/apiCredentials/"
            . $apiCredentialId . "/generateClientKey";
        return $this->requestHttp($url, 'post', $params);
    }
```

2022-02-25 08:34 UTC, AlexandrosMor commented on src/Adyen/Service/Management.php
> +        $this->companyWebhooks = new CompanyWebhooks($this);
I do not see why to add the `null` as parameter as parameter, If we add the null is only for the endpoint checking  [here](https://github.com/Adyen/adyen-php-api-library/blob/PW-6124/src/Adyen/Service/AbstractResource.php#L43)

2022-02-25 13:23 UTC, michaelpaul approved these changes

2022-02-28 12:04 UTC, acampos1916 approved these changes

2022-02-28 12:09 UTC, merged