Release 14.0.0
Adyen/adyen-php-api-library pull request #456
Opened 2023-03-16 07:30 UTC by wboereboom

**Description**
- #442
- #443 
- #455

2023-03-16 08:56 UTC, jillingk commented
Let's quickly merge #430 as well before we release.

2023-03-16 15:22 UTC, Morerice requested changes

2023-03-16 15:22 UTC, Morerice commented on src/Adyen/HttpClient/CurlClient.php
> +        if ($method === (self::HTTP_METHOD_GET || self::HTTP_METHOD_DELETE)  && !empty($params)) {
```suggestion
        if (in_array($method, [self::HTTP_METHOD_GET, self::HTTP_METHOD_DELETE]) && !empty($params)) {
```

2023-03-16 15:22 UTC, Morerice commented on tests/Unit/TestCaseMock.php
> +                if ($client->getLogger() && !is_null($json)) {
```suggestion
                if ($client->getLogger() && isset($json)) {
```

2023-03-17 14:13 UTC, jillingk submitted a review, later dismissed

2023-03-20 08:43 UTC, michaelpaul submitted a review, later dismissed

2023-03-20 09:05 UTC, jillingk approved these changes

2023-03-20 09:59 UTC, michaelpaul approved these changes

2023-03-20 10:25 UTC, merged