CurlClient request fix
Adyen/adyen-php-api-library pull request #464
Opened 2023-03-30 07:47 UTC by jillingk

**Description**
This PR prevents a small bug in the client that throws a curl error even though the request has been successful. This happens because an if statement catches an empty response, which is often the case with a Delete request. The fix adds an extra statement checking again if the result code is 200-204, to prevent this from happening.

**Fixed issue**: #462

2023-04-07 08:28 UTC, wboereboom requested changes

2023-04-07 08:28 UTC, wboereboom commented on src/Adyen/HttpClient/CurlClient.php
>          if (!in_array($httpStatus, $resultOKHttpStatusCodes) && $result) {
This code block is repeated 3 times in this class. can we generalise this to reduce code duplication?

2023-04-14 12:14 UTC, wboereboom approved these changes

2023-04-14 12:15 UTC, AlexandrosMor approved these changes

2023-04-14 12:54 UTC, merged