ITT-413: Data Protection API
Adyen/adyen-php-api-library pull request #480
Opened 2023-04-06 15:03 UTC by michaelpaul

**Description**

Add support for the [Data Protection API](https://docs.adyen.com/development-resources/data-protection-api). 

**Tested scenarios**

- unit tests

2023-04-06 15:39 UTC, AlexandrosMor submitted a review, later dismissed

2023-04-07 07:55 UTC, wboereboom approved these changes

2023-04-07 07:56 UTC, wboereboom requested changes
Some linting issues in model. maybe due to template changes?

2023-04-07 09:37 UTC, michaelpaul commented
> Some linting issues in model. maybe due to template changes?

Fixed in d71d50df0fb3e363d4bc9733ce8e521cd151a76e

2023-04-07 09:43 UTC, AlexandrosMor approved these changes

2023-04-07 11:21 UTC, wboereboom approved these changes
Thanks! Approved 🚀

2023-04-07 11:21 UTC, merged