[ITT-546] Generate capital service
Adyen/adyen-php-api-library pull request #506
Opened 2023-05-17 14:55 UTC by antolo-arch

**Description**
Generate capital service

**Tested scenarios**
UT

2023-05-22 12:21 UTC, jillingk requested changes

2023-05-22 12:21 UTC, jillingk commented on src/Adyen/Client.php
> +    const API_CAPITAL_VERSION = "v3";
```suggestion
```
No need to add this here.

2023-05-22 12:21 UTC, jillingk commented on tests/Unit/CapitalTest.php
> +        $this->assertEquals(0, $result->getGrants()[0]->getAmount()->getValue());
Add a little test here to verify the url, look at other tests to see how (eg LEM or BCL)

2023-05-24 11:11 UTC, michaelpaul approved these changes

2023-05-24 11:26 UTC, jillingk approved these changes

2023-05-24 11:26 UTC, merged