Release v15.1.0
Adyen/adyen-php-api-library pull request #525
Opened 2023-07-21 13:44 UTC by AdyenAutomationBot

Merged pull requests to be released:
- #352
- #352
- #352
- #352
- #358
- #358
- #358
- #358
- #428
- #458
- #499
- #501
- #499
- #499
- #503
- #503
- #506
- #509
- #509
- #512
- #509
- #512
- #512
- #515
- #515
- #428
- #428
- #517
- #507
- #504
- #358
- #514
- #521
- #521
- #518
- #524

2023-07-21 14:28 UTC, michaelpaul requested changes
Version v15.1.0 is incorrect. The release should be done manually because the automation does not support pre-releases yet.

2023-07-25 09:25 UTC, michaelpaul commented on src/Adyen/Client.php
> +    const LIB_VERSION = "15.1.0";
Beta exit shall be done manually. 
```suggestion
    const LIB_VERSION = "15.0.0";
```

2023-08-07 15:01 UTC, michaelpaul approved these changes

2023-08-07 15:02 UTC, jillingk approved these changes

2023-08-07 15:29 UTC, Aleffio approved these changes

2023-08-07 15:30 UTC, wboereboom approved these changes

2023-08-08 07:43 UTC, michaelpaul approved these changes

2023-08-08 08:05 UTC, merged